version: '3'

services:
  ikebukuro_homepage:
    container_name: ikebukuro_homepage
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./public:/usr/src/app/public
    
volumes:
  logvolume01: {}
  public: